/* @LICENSE(NICTA) */

/* This header was generated by kernel/tools/invocation_header_gen.py.
 *
 * To add an invocation call number, edit libsel4/include/interfaces/sel4.xml.
 *
 */
#ifndef __LIBSEL4_ARCH_INVOCATION_H
#define __LIBSEL4_ARCH_INVOCATION_H

enum arch_invocation_label {
    RISCVPageDirectoryMap = nInvocationLabels + 0,
    RISCVPageDirectoryUnmap = nInvocationLabels + 1,
    RISCVPageTableMap = nInvocationLabels + 2,
    RISCVPageTableUnmap = nInvocationLabels + 3,
    RISCVPageMap = nInvocationLabels + 4,
    RISCVPageUnmap = nInvocationLabels + 5,
    RISCVPageClean_Data = nInvocationLabels + 6,
    RISCVPageGetAddress = nInvocationLabels + 7,
    nArchInvocationLabels
};

#endif /* __LIBSEL4_ARCH_INVOCATION_H */
